-- Migration 001: Extensions and Enums
-- Anjanvel ERP

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

CREATE TYPE user_role AS ENUM (
  'OWNER', 'MANAGER', 'HOUSEKEEPING', 'KITCHEN',
  'ACTIVITY_COORDINATOR', 'SHOP_OPERATOR', 'ACCOUNTANT', 'GUIDE'
);
CREATE TYPE booking_status AS ENUM (
  'INQUIRY', 'CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED', 'NO_SHOW'
);
CREATE TYPE payment_status AS ENUM ('PENDING', 'PARTIAL', 'PAID', 'REFUNDED', 'FAILED');
CREATE TYPE payment_method AS ENUM ('CASH', 'UPI', 'CARD', 'ONLINE', 'BANK_TRANSFER');
CREATE TYPE room_status AS ENUM ('AVAILABLE', 'OCCUPIED', 'RESERVED', 'CLEANING', 'MAINTENANCE');
CREATE TYPE package_type AS ENUM (
  'DAY_PICNIC', 'OVERNIGHT_STAY', 'CORPORATE_RETREAT', 'SCHOOL_CAMP',
  'HERITAGE_PACKAGE', 'FARM_EXPERIENCE', 'WORKSHOP', 'FESTIVAL_PACKAGE'
);
CREATE TYPE lead_source AS ENUM (
  'WEBSITE', 'INSTAGRAM', 'WHATSAPP', 'GOOGLE', 'PHONE', 'WALK_IN', 'REFERRAL'
);
CREATE TYPE lead_status AS ENUM ('NEW', 'CONTACTED', 'FOLLOW_UP', 'QUALIFIED', 'CONVERTED', 'LOST');
CREATE TYPE food_type AS ENUM ('VEG', 'NON_VEG', 'JAIN', 'VEGAN', 'SATVIK');
CREATE TYPE meal_type AS ENUM ('BREAKFAST', 'LUNCH', 'DINNER', 'SNACKS', 'HIGH_TEA');
CREATE TYPE order_status AS ENUM ('PENDING', 'PREPARING', 'READY', 'SERVED', 'CANCELLED');
CREATE TYPE task_status AS ENUM ('PENDING', 'IN_PROGRESS', 'DONE', 'SKIPPED');
CREATE TYPE ticket_status AS ENUM ('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED');
CREATE TYPE ticket_priority AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'URGENT');
CREATE TYPE inventory_category AS ENUM ('KITCHEN', 'HOUSEKEEPING', 'FARM', 'MAINTENANCE', 'SHOP');
CREATE TYPE transaction_type AS ENUM ('IN', 'OUT', 'ADJUSTMENT', 'DAMAGE', 'RETURN');
CREATE TYPE activity_status AS ENUM ('ACTIVE', 'CANCELLED', 'COMPLETED', 'FULL');
CREATE TYPE gender AS ENUM ('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY');
CREATE TYPE id_type AS ENUM ('AADHAAR', 'PASSPORT', 'DRIVING_LICENSE', 'PAN', 'VOTER_ID');
